enableTelemetry: false

nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com/dchilkur":
    npmAuthToken: "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"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
